version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch-oss
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    container_name: logstash-oss
    links:
      - elasticsearch:elasticsearch
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
      - ../data/:/data/
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    container_name: kibana-oss
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5603:5601

